# Generated by Django 4.0.6 on 2022-09-30 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_name', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('websiteInfo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromSource', models.CharField(max_length=100)),
                ('toDestination', models.CharField(max_length=100)),
                ('departureTime', models.CharField(max_length=100)),
                ('estimatedArrivalTime', models.CharField(max_length=100)),
                ('firstTakeOff', models.CharField(max_length=100)),
                ('secondTakeOff', models.CharField(max_length=100)),
                ('fare', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.CharField(max_length=300)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.operator')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('town', models.CharField(max_length=50)),
                ('operator_info', models.CharField(max_length=70)),
                ('operators', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.operator')),
            ],
        ),
    ]
