# Generated by Django 4.0.6 on 2022-10-08 03:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takeoff',
            name='trip',
        ),
        migrations.AddField(
            model_name='takeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 10, 7, 20, 8, 49, 243751)),
        ),
        migrations.AddField(
            model_name='trip',
            name='take_off',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='takeoff', to='myapp.takeoff'),
        ),
        migrations.AlterField(
            model_name='route',
            name='duration',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
