# Generated by Django 4.1.3 on 2022-11-03 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_operator_point_remove_booking_trip_id_booking_fare_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='time',
            new_name='datetime',
        ),
    ]
